### ISSUE TITLE
yard is in conflict with nodejs

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/peertube_ynh#13]
i just tried an install using : 
`yunohost app install https://github.com/YunoHost-Apps/peertube_ynh/tree/testing`

but it failed : 
```
Attention : dpkg: concernant yarn_1.5.1_all.deb contenant yarn :
Attention :  yarn entre en conflit avec nodejs (<< 4.0.0)
Attention :   « nodejs » (version « 0.10.29~dfsg-2 ») est présent ainsi que « installé ».
Attention : 
Attention : dpkg: erreur de traitement de l'archive yarn_1.5.1_all.deb (--install) :
Attention :  paquets en conflit - yarn non installé
Attention : Des erreurs ont été rencontrées pendant l'exécution :
Attention :  yarn_1.5.1_all.deb
Attention : !!
Attention :   peertube's script has encountered an error. Its execution was cancelled.
Attention : !!
```
tell me if you need a full log, i can reproduce it ;)

```
yunohost -v
yunohost: 
  repo: stable
  version: 2.7.10
yunohost-admin: 
  repo: stable
  version: 2.7.7
moulinette: 
  repo: stable
  version: 2.7.7
ssowat: 
  repo: stable
  version: 2.7.7
```
