### ISSUE TITLE
Server Tool: prune-storage.js: Cannot prune storage

### ISSUE THREAD

**Issue by AkselRocks** [YunoHost-Apps/peertube_ynh#193]
**Describe the bug**
When using peertube Server tool "prune-storage.js", error occurs: "Cannot prune storage because you put multiple storage keys in the same directory."

Seems to be this issue: https://github.com/Chocobozzz/PeerTube/issues/2128 
Solution: All keys need to be in another directory.

On yunohost server: /var/www/peertube/config/production.yaml:
```
storage:
  tmp: '/home/yunohost.app/peertube/storage/tmp/' # Use to download data (imports etc), store uploa$
  avatars: '/home/yunohost.app/peertube/storage/avatars/'
  videos: '/home/yunohost.app/peertube/storage/videos/'
  streaming_playlists: '/home/yunohost.app/peertube/storage/streaming-playlists/'
  redundancy: '/home/yunohost.app/peertube/storage/videos/'
```
"Video" and "redundancy" are the same directories.

**Versions**
- Hardware: VPS bought online 
- YunoHost version: 4.0.8.3
- I have access to my server: Through SSH 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: no 

**To Reproduce**
```
/var/www/peertube/config$ sudo systemctl stop peertube && sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run prune-storage

> peertube@2.4.0 prune-storage /var/www/peertube
> node ./dist/scripts/prune-storage.js

Cannot prune storage because you put multiple storage keys in the same directory.

```

**Expected behavior**
no fail, prune storage.

**Logs**
