### ISSUE TITLE
upgrade 4.2.2~ynh2 to 4.3.1~ynh1 is KO

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/peertube_ynh#355]
### Describe the bug
upgrade via cli from `4.2.2~ynh2` to `4.3.1~ynh1`

### Context

- Hardware: VPS bought online
- YunoHost version: 
```
yunohost: 
  repo: stable
  version: 11.0.10.2
yunohost-admin: 
  repo: stable
  version: 11.0.11
moulinette: 
  repo: stable
  version: 11.0.9
ssowat: 
  repo: stable
  version: 11.0.9
```
- I have access to my server: 
Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: 
no
- Using, or trying to install package version/branch: 4.3.1~ynh1 stable
- If upgrading, current package version:  4.2.2~ynh2 

### Steps to reproduce
    ```sh
    sudo yunohost app upgrade peertube
    ```
### Expected behavior
upgrade expected

### Logs

https://paste.yunohost.org/raw/oqemopujif
