### ISSUE TITLE
Upgrade from 5.2.1 to 6.0.2 fails

### ISSUE THREAD

**Issue by TILvids** [YunoHost-Apps/peertube_ynh#416]
Here's the yunopaste. Any ideas?

https://paste.yunohost.org/raw/agabodumig

**Comment by isAAAc** [comment]
```
root@krashboyz:~# yunohost --version
yunohost: 
  repo: stable
  version: 11.2.9.1
yunohost-admin: 
  repo: stable
  version: 11.2.4
moulinette: 
  repo: stable
  version: 11.2
ssowat: 
  repo: stable
  version: 11.2
```

Same here 
https://paste.yunohost.org/raw/anovapozim
