### ISSUE TITLE
Enabling rtmps properly

### ISSUE THREAD

**Issue by Ryvix** [YunoHost-Apps/peertube_ynh#460]
While what I did seems to have successfully enabled rtmps support in Peertube, this is more of an inquiry of if I did this the proper way or if there is a better way. I'm also wondering if there will be any issues the way I did it since I am not very familiar with yunohost or peertube and I am noticing that the certs are in a non-standard folder. Maybe the config file I edited will get overwritten?

Maybe if this is a good way to do it then the peertube user could be added to the ssl-certs group by default and rtmps support could be optionally enabled, perhaps by providing a toggle in the UI for enabling it?

Thank you!

### Context

- YunoHost version: 12.0.7

### Steps to reproduce

- Install Peertube through yunohost
- rtmps is not enabled by default
- edit /etc/yunohost/apps/peertube/conf/production.yaml:
```
  rtmps:
    enabled: true

    # Listening hostname/port for RTMPS server
    # '::' to listen on IPv6 and IPv4, '0.0.0.0' to listen on IPv4
    # Use null to automatically listen on '::' if IPv6 is available, or '0.0.0.0' otherwise
    hostname: null
    port: 1936

    # Absolute paths
    key_file: '/etc/yunohost/certs/video.example.com/key.pem'
    cert_file: '/etc/yunohost/certs/video.example.com/crt.pem'

    # Public hostname of your RTMPS server
    # Use null to use the same value than `webserver.hostname`
    public_hostname: null
```
- restart peertube
- error that it has no permission to cert files when trying to enable rtmps
- run command to add peertube to the ssl-cert group:
`# usermod -aG ssl-cert peertube`
- restart peertube and rtmps is enabled and seems to work fine
